apiVersion: v1
kind: Pod
metadata:
  name: busy
  labels:
    app: busy
spec:
  containers:
  - name: c1
    image: 'radial/busyboxplus:curl'
    command: ['sh', '-c', 'while true; do sleep 3d; done' ]

