apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels: 
    app: web
    kubernetes.io/zone: europe
    dmz: "false"
  annotations:
    version: "v1.0, patch 312738"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

