apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: second-pod
  name: second-pod
spec:
  containers:
  - image: nginx:1.19.2
    name: second-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
