apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu
  name: ubuntu-pod
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    command: ['sh', '-c', 'tail -F /var/test']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
