apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  initContainers:
  - name: prepare
    image: alpine:3.2
    command: ['sh', '-c', 'apk update; apk add git; git clone -b develop https://github.com/mariano-italiano/lx-k_Jul.git /data; echo "Init containter completed successfully"'] 
    volumeMounts:
    - name: sharedvol
      mountPath: /data
  containers:
  - name: web
    image: nginx:1.19.2
    volumeMounts:
    - name: sharedvol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: sharedvol
    emptyDir: {} 
