apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-pod
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/busybox:1.27.2
    command: ['sh', '-c', 'touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600']
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
