apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinity-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/storage
            operator: In
            values:
            - gold
            - platinum
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/zone
            operator: In
            values:
            - secure
  containers:
  - name: with-node-affinity
    image: registry.k8s.io/pause:3.8
