apiVersion: v1
kind: Pod
metadata:
  name: podantyaffinity-pod
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: storage
              operator: In
              values:
              - gold
          topologyKey: kubernetes.io/storage
  containers:
  - name: with-pod-affinity
    image: registry.k8s.io/pause:3.8
