apiVersion: v1
kind: Pod
metadata:
  name: toleration-execute-pod
spec:
  containers:
  - image: nginx:1.19.2
    name: c1
  tolerations:
  - key: "kubernetes.io/zone"
    operator: "Equal"
    value: "dmz"
    effect: "NoSchedule"
  - key: "kubernetes.io/env"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 60
